# -*- coding: utf-8 -*-
"""minutesmaker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkPczFpfdL9ek6IiDgYeMeEPTIn3lqBu
"""

!pip install ffmpeg-python

import ffmpeg

pip install git+https://github.com/openai/whisper.git

import whisper

model = whisper.load_model("medium")
result = model.transcribe("<file path>")
print(result["text"])

print(result)